import type { Metadata } from "next";
import { Bricolage_Grotesque, Oswald } from "next/font/google";
import localFont from "next/font/local";
import localFont2 from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

const MainFont = Bricolage_Grotesque({ subsets: ["latin"] });
const OswaldFont = Oswald({ subsets: ["latin"], variable: "--font-oswald" });
const PixelFont = localFont({
  src: "../public/assets/fonts/GaMaamli-Regular.ttf",
  variable: "--font-pixel",
});
const PixelFont2 = localFont2({
  src: "../public/assets/fonts/PixelifySans-VariableFont_wght.ttf",
  variable: "--font-pixel2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(MainFont.className, OswaldFont.variable, PixelFont.variable, PixelFont2.variable)}>
        {children}
      </body>
    </html>
  );
}
